modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "crash_assistant"
version = "${version}"
displayName = "Crash Assistant"
authors = "KostromDan"
description = '''
Shows a GUI after Minecraft crashes, immediately showing all affected logs, crash reports, or hs_err files. Provides a one-click solution to upload them, copy the link, and perform other actions for easier reporting, debugging, and troubleshooting.
'''
#logoFile = ""

[[dependencies.crash_assistant]]
modId = "forge"
mandatory = true
versionRange = "[43.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crash_assistant]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crash_assistant]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
